apiVersion: v1
kind: Pod
metadata:
  name: bad-privileged
spec:
  containers:
    - name: bad
      image: busybox:latest
      command: ["sleep", "3600"]
      securityContext:
        privileged: true
